### ISSUE TITLE
cannot read property 'output' of undefined

### ISSUE THREAD

**Issue by timbakkum** [emgeee/gulp-standard#37]
Hi,

I can't seem to get the plugin to work. We have the following setup, passing in an array of file paths to the plugin. 

``` javascript 
module.exports = function(plugins, config) {

	plugins.gulp.task('js', function() {
		return plugins.gulp.src(config.javascript)
			.pipe(plugins.plumber())
			.pipe(plugins.standard())
      .pipe(plugins.standard.reporter('default', {
        breakOnError: false,
        quiet: true
      }))
			.pipe(config.production ? plugins.uglify() : plugins.util.noop())
			.pipe(plugins.gulp.dest(config.path.dist + config.folder.js))
			.pipe(plugins.browserSync.reload({stream: true})); 
	});

};
```

config.javascript in our case is equal to: 
``` javascript 
[ './node_modules/requirejs/require.js',
  './node_modules/flickity/dist/flickity.pkgd.js',
  './src/js/*.js',
  './src/js/modules/*.js' ]
```
I get the following error, results is an empty array: 
```
node_modules/gulp-standard/index.js:26
      if (data.results[0].output) {
                         ^

TypeError: Cannot read property 'output' of undefined
```

**Comment by stephenlacy** [comment]
What is the version of `gulp-standard` and the version of `standard` installed?

**Comment by timbakkum** [comment]
Currently using:
"standard": "^10.0.3",
"gulp-standard": "^10.1.1"

can it have to do with the version of Node used?

**Comment by davidlaym** [comment]
reporting same error

```
  "gulp": "^3.9.1",
  "standard": "^10.0.3",
  "gulp-standard": "^10.1.1",
```

```
<omited-full-path>\node_modules\gulp-standard\index.js:26
      if (data.results[0].output) {
                          ^

TypeError: Cannot read property 'output' of undefined
    at <omited-full-path>\node_modules\gulp-standard\index.js:26:27
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```

**Comment by ghost** [comment]
I'm getting the same error.
```
[17:11:49] Starting 'standard'...
.../node_modules/gulp-standard/index.js:26
      if (data.results[0].output) {
                          ^

TypeError: Cannot read property 'output' of undefined
    at .../node_modules/gulp-standard/index.js:26:27
    at _combinedTickCallback (internal/process/next_tick.js:138:11)
    at process._tickCallback (internal/process/next_tick.js:180:9)
```
Here is my gulpfile.js:
```
const gulp = require('gulp')
const standard = require('gulp-standard')

gulp.task('standard', () => {
  return gulp.src('./**/*.js')
    .pipe(standard())
    .pipe(standard.reporter('default'))
})

gulp.task('default', ['standard'])
```

**Comment by ghost** [comment]
It somehow breaks in all of the cases above because you're trying to lint files in the `node_modules/` folder, while `standard` ignores these files by default.
